### ISSUE TITLE
展会招募-详情页-参展供应商产品排列有问题

### ISSUE THREAD

**Issue by aaamed** [wzlee/aaamed-issue#10]
![image](https://user-images.githubusercontent.com/58673979/70405290-a03cf000-1a77-11ea-8032-96d7ad105ee2.png)

**Comment by jerry-ct** [comment]
你好，这是之前要求改动全局响应宽度影响的，是按之前设计稿固定的尺寸，如果要写成自适应就不能固定宽高，跟https://github.com/wzlee/aaamed-issue/issues/11这条issues提的高度要固定就是相背的，麻烦确认下设计需求

**Comment by aaamed** [comment]
按照这个bug来修改，第三个和上面的并排排列

**Comment by jerry-ct** [comment]
好的

**Comment by jerry-ct** [comment]
已修复
