### ISSUE TITLE
展会招募-详情页-参展供应商，产品白底高度不对， 最下方文字和底边 边距不对

### ISSUE THREAD

**Issue by aaamed** [wzlee/aaamed-issue#11]
![image](https://user-images.githubusercontent.com/58673979/70405308-b185fc80-1a77-11ea-9cde-7427ece753fd.png)
请参照红框内三个数值修改
![image](https://user-images.githubusercontent.com/58673979/70405313-b8ad0a80-1a77-11ea-95a4-354268d29620.png)

**Comment by jerry-ct** [comment]
高度不固定，边距已调整，宽高度自适应

**Comment by jerry-ct** [comment]
高度不固定，边距已调整，宽高度自适应，已修复
