### ISSUE TITLE
展会招募/展会活动-详情页

### ISSUE THREAD

**Issue by aaamed** [wzlee/aaamed-issue#12]
插入视频最大“显示宽度”为：1120px，若视频实际尺寸宽度大于1120px，则按照比例缩小至此尺寸宽度去显示；视频尺寸若小于此宽度，则按照实际大小显示
![image](https://user-images.githubusercontent.com/58673979/70405346-d8443300-1a77-11ea-8429-144c3fdef826.png)
![image](https://user-images.githubusercontent.com/58673979/70405349-daa68d00-1a77-11ea-9cd7-112f0bef3df4.png)

**Comment by wzlee** [comment]
无法实现
