### ISSUE TITLE
供应商后台

### ISSUE THREAD

**Issue by aaamed** [wzlee/aaamed-issue#13]
![image](https://user-images.githubusercontent.com/58673979/70405373-ee51f380-1a77-11ea-9f19-eebf094f7dbd.png)
供应商后台主页
左边栏三个标题
选中后样式
![image](https://user-images.githubusercontent.com/58673979/70405390-f5790180-1a77-11ea-9db0-190127c75eac.png)

**Comment by wzlee** [comment]
不予处理，设计稿没有选中效果
