### ISSUE TITLE
运营后台-所有列表页面-审核或查看产品详情后，关掉窗口后就不知道是查看/审核的是哪个产品了

### ISSUE THREAD

**Issue by aaamed** [wzlee/aaamed-issue#14]
![image](https://user-images.githubusercontent.com/58673979/70405412-0de91c00-1a78-11ea-925b-7edc09443077.png)
对某个产品操作审核或者查看之后，这条信息保持选中样式（如左图所示蓝色#eaf7fe底色）
增加列表行的active样式为：背景色#eaf7fe

**Comment by wzlee** [comment]
尝试了很多种方案，都无法无法实现该需求
