### ISSUE TITLE
产品详情页 未做适配

### ISSUE THREAD

**Issue by aaamed** [wzlee/aaamed-issue#8]
产品详情页在1280px屏幕下，
要保证右边“店铺信息”
和“猜你喜欢”的显示，如
右图所示
![image](https://user-images.githubusercontent.com/58673979/70405229-69ff7080-1a77-11ea-9e72-a7a04c0ee6b5.png)
![image](https://user-images.githubusercontent.com/58673979/70405234-6e2b8e00-1a77-11ea-9788-7a967fe8b4db.png)

**Comment by wzlee** [comment]
属于新需求，需沟通相关开发费用
